# Generated by Django 3.2.4 on 2021-07-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HBP', models.BooleanField()),
                ('Fever', models.BooleanField()),
                ('nauseous', models.BooleanField()),
                ('aches', models.BooleanField()),
                ('Sweat', models.BooleanField()),
                ('Diarrhea', models.BooleanField()),
                ('fatigue', models.BooleanField()),
                ('AbdominalPain', models.BooleanField()),
                ('Headache', models.BooleanField()),
                ('HeartPain', models.BooleanField()),
            ],
        ),
    ]
